cat producing weird spacing issue with pipes

diff --git a/testing/testall b/testing/testall
--- a/testing/testall
+++ b/testing/testall
@@ -1,2 +1,25 @@
 #!/bin/zsh
-./test_basic_commands
+run_test() {
+    testname=$1
+    if [ -f $testname.diff ];
+    then
+        rm $testname.diff
+    fi
+    echo -e "\033[1;33m\nRunning $testname\033[0m"
+    ./$testname
+    if [ $? -ne 0 ] 
+    then
+        echo
+        echo -e "\033[1;31m$testname Failed\033[0m"
+    else
+        echo
+        echo -e "\033[1;32m$testname Passed\033[0m"
+    fi
+    cat $testname.diff >> testall.diff
+}
+if [ -f testall.diff ];
+then 
+    rm testall.diff
+fi
+run_test test_basic_commands
+run_test test_redirect_input
